tasks:
  - name: scenario-setup
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" | tee -a $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' | tee -a $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash | tee -a ./katapod_logs/astra-cli-install.log
    init: |
      docker pull cassandra:4.1
      pip install -r client_application/requirements.txt
      ./scenario_scripts/configure-ssh.sh  | tee -a ./katapod_logs/astra-cli-install.log
    command: |
      docker run \
        --name cassandra-origin-1 \
        -v ${PWD}/origin_config/cassandra.yaml:/etc/cassandra/cassandra.yaml \
        -d \
        cassandra:4.1
      source /home/gitpod/.astra/cli/astra-init.sh
ports:
  - port: 22
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 9042
    onOpen: ignore
  - port: 9090
    onOpen: ignore
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/0.6.1-multiterminals-beta2/katapod-0.6.1-multiterminals-beta2.vsix
